package com.a18.common.constant;

public interface PreDefinedRole {
  String
      ROLE_TRUSTED_CLIENT = "ROLE_TRUSTED_CLIENT",
      ROLE_CLIENT = "ROLE_TRUSTED_CLIENT",
      ROLE_USER = "ROLE_USER",
      ROLE_STAFF = "ROLE_STAFF",
      ROLE_ADMIN = "ROLE_ADMIN",
      ROLE_PAYMENT_STAFF = "ROLE_PAYMENT_STAFF",
      ROLE_PAYMENT_HEAD = "ROLE_PAYMENT_HEAD",
      ROLE_MARKETING_STAFF = "ROLE_MARKETING_STAFF",
      ROLE_MARKETING_HEAD = "ROLE_MARKETING_HEAD",
      ROLE_CS_STAFF = "ROLE_CS_STAFF",
      ROLE_CS_HEAD = "ROLE_CS_HEAD";
}
